spring:
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/goods?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: lingcai1910

  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /store


mybatis:
  mapper-locations: classpath:mapper/*.xml